### ISSUE TITLE
Could you integrate pyenv as well?

### ISSUE THREAD

**Issue by codingbutstillalive** [thehale/docker-python-poetry#2]

**Comment by thehale** [comment]
**What benefit would `pyenv` offer that can't be obtained by switching between Docker images?**

We already build multiple images for all supported Python versions (current 3.6-3.11). 

I'm hesitant to add additional packages to the default image because we want it to stay as small/lightweight as possible.

**Comment by codingbutstillalive** [comment]
Thanks for your quick reply.

Well, the idea was to have this handy as a flexible Data Science 'platform', which you can use for various projects.

I often browse through github projects and found that I need to flexibly adjust to various Python dependencies.

On my local machine, this works quite good with pyenv+poetry.

So, maybe this is not what you intended. I now see that the concept of a devcontainer is more static than what I have in mind, i.e. a flexible "from scratch" platform.

**Comment by thehale** [comment]
Makes sense. I also use Poetry/pyenv for my own development environment and greatly appreciate their combined flexibility for development work.

However, this particular project is not the right place to combine those two tools into a single container:
1. This project's primary use case serves CI builds requiring a Poetry installation, *not* multi-purpose local devcontainers.
2. Adding pyenv would require switching to a base Linux image (Ubuntu/Alpine) instead of basing off of the official Python images -- a fairly substantial change which would make the Dockerfile harder to read.

As such, I will close this issue as out of scope for this project, even though I support this concept as an independent project.
